//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAILY_LIFE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public int user_id { get; set; }
        public string user_code { get; set; }
        public string user_username { get; set; }
        public string user_password { get; set; }
        public string user_firstname { get; set; }
        public string user_lastname { get; set; }
    }
}
