//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAILY_LIFE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_type
    {
        public int user_type_id { get; set; }
        public string user_type_name { get; set; }
    }
}
